apiVersion: apps/v1
kind: deployment
metadata:
  name: myapp-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    mathchLabels:
      app: myapp-deploy
      release:  canary
  template:
    metadata: 
      labes:
        app: myapp
        release: canary
    spec:
      containers:
        - name: myapp
          image: ikubernetes/myapp:v1
          ports:
            - name: http
              containersPort: 80
